# Node.js dependencies
  node_modules/
  
  # Logs
    logs/
  *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
  
  # OS-specific files
    .DS_Store
    Thumbs.db
  
  # Environment files
    .env
  
  # Build directories
    /dist
    /build
  
  # Dependency directories (for package managers other than npm)
    .bower_components/
    .pnp/
    .pnp.js
  
  # IDE or text editor files
    .vscode/
    .idea/
  *.sublime-workspace
  *.sublime-project
  
  # Operating System files
  *.swp
  *.swo
  *.target/
  *.mvn/
.idea/
.fastRequest/
.DS_Store
  **/.idea/
  
  **/.mvn
  **/.mvnw